# Uvod

Ta knjiga vsebuje gradiva za izvedbo laboratorijskih vaj pri predmetu Numerična matematika
na Fakulteti za računalništvo in informatiko, Univerze v Ljubljani. 

Knjige o numerični matematiki se pogosto posvečajo predvsem matematičnim vprašanjem. Vsebina te knjige pa poskuša nasloviti bolj praktične vidike numerične matematike. Tako so primeri, če je le mogoče, povezani s problemom praktične narave s področja fizke, matematičnega modeliranja in računalništva, pri katerih lahko za rešitev problema uporabimo numerične metode.  

Bralcu svetujemo, da vso kodo napiše in preiskusi sam. Še bolje je, če kodo razšiti in spreminja. Bralca spodbujamo, da se čim bolj igra z napisano kodo. Koda, ki je navedena v tej knjigi, je minimalna različica kode, ki reši določen problem in še ustreza minimalnim standardom pisanja kvalitetne kode. Pogosto izpustimo preverbe ali implementacijo robnih primerov. Včasih opustimo obravnavo pričakovanih napak. Prednost smo dali berljivosti, pred kompletnostjo, da je bralcu lažje razumeti, kaj koda počne. 

Knjiga je napisana kot literarni program. Izvorna koda knjige je namreč tudi program, s katerim so
generirane vse slike in prikazane vrednosti v knjigi. Več o literarnem programiranju je opisano v 
@knuth84.
