project:
  type: book

book:
  title: "Numerična matematika in programski jezik Julia"
  author: "Martin Vuk"
  date: "2024-02-20"
  date-format: "D. M. YYYY"
  repo-url: https://github.com/mrcinv/nummat-julia
  repo-actions: [edit]
  downloads: [pdf]
  language: sl
  chapters:
    - index.qmd
    - 00_uvod.qmd
    - 01_julia.qmd
    - 02_koren.qmd
    - 03_tridiag.md
    
    #- part: domace.qmd
    #- part: izpiti.qmd
    - reference.qmd

bibliography: references.bib
language: sl.yml

highlight-style: pygments

format:
  html:
    theme: cosmo
    code-copy: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    papersize: a4
jupyter: julia-1.10


